version: "3"
services:
  twilio-app:
    build: 
      dockerfile: Dockerfile
      context: .
    restart: always
    volumes:
      - ./src:/app/src
    ports:
      - "3050:3000"
    # env_file: 
    #   - ./.env
    
